[package]
name = "cosmonaut-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
rocket = { version = "0.5.1", features = ["json", "uuid"] }

[dev-dependencies]
cosmonaut-server = { path = "." }
